# SPDX-FileCopyrightText: 2022 Gleb Smirnov <glebsmirnov0708@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

branches: [main]

plugins:
  - '@semantic-release/release-notes-generator'
  -
    - '@semantic-release/commit-analyzer'
    - preset: angular
      releaseRules:

      - type: po
        release: patch

      - type: metainfo
        release: patch
  -
    - '@semantic-release/exec'
    - prepareCmd: ci/prepare-release.sh ${nextRelease.version}
    - success: ci/release-to-flathub.sh
  -
    - '@semantic-release/git'
    - assets:
      - CHANGELOG.md
      - meson.build
      - data/*.appdata.xml.in
      - NEXT-RELEASE.xml
      - build-aux/flatpak/*.yaml
  - '@semantic-release/github'
