# SPDX-FileCopyrightText: 2022 Gleb Smirnov <glebsmirnov0708@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

branches: [main]

plugins:
  - @semantic-release/github
  - @semantic-release/release-notes-generator
  - @semantic-release/changelog
  -
    - @semantic-release/commit-analyzer
    - preset: angular
      releaseRules:

      - type: po
        release: patch

      - type: metainfo
        release: patch
  -
    - @semantic-release/git
    - assets:
      - CHANGELOG.md
  -
    - @semantic-release/exec
    - prepareCmd: ci/prepare-release.sh ${nextRelease.version}
