# SPDX-FileCopyrightText: 2022 Gleb Smirnov <glebsmirnov0708@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

on:
  push:
  pull_request:

name: CI

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1.1.1

  flatpak:
    name: Flatpak
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: textpieces.flatpak
        manifest-path: build-aux/flatpak/com.github.liferooter.textpieces.yaml
        run-tests: true
        cache-key: flatpak-builder-${{ github.sha }}

  update-po:
    name: Update translations
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-42
      options: --privileged
    steps:

    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git --version
        git config --global --add safe.directory $(pwd)
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'

    - name: Add Flathub repository
      run: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install dependencies
      run: >
        xvfb-run -a -s "-screen 0 1024x768x24"
        flatpak-builder --keep-build-dirs --user --install-deps-from=flathub --disable-rofiles-fuse flatpak_app --stop-at=textpieces build-aux/flatpak/com.github.liferooter.textpieces.yaml


    - name: Update translations
      run: >
        xvfb-run -a -s "-screen 0 1024x768x24"
        flatpak-builder --run flatpak_app build-aux/flatpak/com.github.liferooter.textpieces.yaml
        ci/update-po.sh

    - name: Push changes to GitHub
      run: git push
