# SPDX-FileCopyrightText: 2022 Gleb Smirnov <glebsmirnov0708@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

on:
  push:
    branches: [main]

name: Release

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: sudo apt install -y --no-install-recommends npm libxml2

    - name: Install semantic-release tool
      run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog@semantic-release/exec

    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: github-actions
        GIT_AUTHOR_EMAIL: github-actions@github.com
        GIT_COMMITTER_NAME: $GIT_AUTHOR_NAME
        GIT_COMMITTER_EMAIL: $GIT_AUTHOR_EMAIL
      run: semantic-release
